### PR TITLE
5. Add Cloverage support

### PR DESCRIPTION
**Pull request by hjhamala**
Cloverage is run and result is parsed from codecov.json. Partial hits are not supported by SonarQube. Also form coverage cannot be added because SonarQube understands only about lines.

### CODE REVIEW

**Comment by hjhamala** [comment]
@fsantiag this is now also ready for code review.

**Comment by hjhamala** [comment]
@fsantiag Cloverage support is now ready for the review.

**Comment by fsantiag** [comment]
After this, we can close #6. It seems other people are waiting for these changes. ;)

**Comment by hjhamala** [comment]
@fsantiag This should be now ready for the merge.

**Pull request merged**
